### ISSUE TITLE
Setup some branch protection rules

### ISSUE THREAD

**Issue by robert-northmind** [bmw-tech/widget_driver#11]
Currently everyone is free to push to master.
We should add some protection rules when/if we get more collaborators.

As soon as we make it public we can set this up.

Recommended rules:

- Only merge to main/master via PRs
- Need 2 approvals on PRs.. By owners
- Add codeowners if possible
- Allow only codeowners to create new branches

**Comment by dominik089** [comment]
Basic Branch protection was set and CODEOWNERS established with PR:45
https://github.com/bmw-tech/widget_driver/pull/45
