### ISSUE TITLE
generator generates code for static fields

### ISSUE THREAD

**Issue by JanMichaelPeter** [bmw-tech/widget_driver#162]
**Describe the bug**
generator generates code for static fields, this leads to a compiler warning since they can't be overridden.

**To Reproduce**
Steps to reproduce the behavior, e.g.:
1. Create new Driver
2. add a (public) static field to driver
3. run generator
4. observe described behavior

**Expected behavior**
the generator runs and ignores static files

**Comment by robert-northmind** [comment]
aha, nice catch. I didn't think about this
