### ISSUE TITLE
Deploy widget_driver_annotations to pub.dev

### ISSUE THREAD

**Issue by robert-northmind** [bmw-tech/widget_driver#21]
We should deploy the first version of the annotations package to pub.dev.

It has no exrternal dependencies so this should be easy.

**Comment by JanMichaelPeter** [comment]
Done with:
https://github.com/bmw-tech/widget_driver/pull/62
https://github.com/bmw-tech/widget_driver/pull/64
https://github.com/bmw-tech/widget_driver/pull/65
