### ISSUE TITLE
Add build pipeline action for master jobs which deploys to Pub.dev

### ISSUE THREAD

**Issue by robert-northmind** [bmw-tech/widget_driver#24]
On all master merges we should run an action which deploys the lastest version to pub.dev.

This of course requirres that each merge to master can deploy.. so we need to have made sure of that before.. at PR level

**Comment by JanMichaelPeter** [comment]
Done with:
https://github.com/bmw-tech/widget_driver/pull/62
https://github.com/bmw-tech/widget_driver/pull/64
https://github.com/bmw-tech/widget_driver/pull/65
