### ISSUE TITLE
Update widget_driver_generator to depend on the annotaion via pub-dev refernece

### ISSUE THREAD

**Issue by robert-northmind** [bmw-tech/widget_driver#25]
Currently it is referencing the annotations via hard coded path. (In pubspec yaml)
Thisa should be changed to be a pub.dev version number reference

**Comment by JanMichaelPeter** [comment]
Done with:
https://github.com/bmw-tech/widget_driver/pull/62
https://github.com/bmw-tech/widget_driver/pull/64
https://github.com/bmw-tech/widget_driver/pull/65
