### ISSUE TITLE
Get access to flutter-dev@bmwgroup.com

### ISSUE THREAD

**Issue by robert-northmind** [bmw-tech/widget_driver#56]
flutter-dev@bmwgroup.com is the official email address registered with the bmw-tech flutter publisher.
It would be good if we somehow can get access to this. So that we can get informed if someone tries to contact this email.

We don't have to have direct access to it. But at least it would be good to know who has access to it.. and inform them that we are the contact persons for questions relating to the `widget_driver` repo.

**Comment by fwagner** [comment]
flutter-dev is a mailing list. It is owned and by Christian and me. It forwards to the Mobile2.0 list, which is basically the core team.

**Comment by robert-northmind** [comment]
@fwagner  Okay cool. Thanks for that quick update 😄   Some info for you then:
We plan to use that email address in our Code_of_conduct.md so people can send emails there if they want to report something.

Then I will close this ticket.
