### ISSUE TITLE
Fix points in pub.dev for widget_driver

### ISSUE THREAD

**Issue by robert-northmind** [bmw-tech/widget_driver#68]
There are some minor issues in some of the packages which leads to them not getting 100% points.
We should look over this and fix the missing config things.
See here:
- https://pub.dev/packages/widget_driver/score

Also make sure to update the example with real content. You can copy an existing example from Readme
Also make sure to fix the broken example image (/packages/doc/resources/counter_widget_demo.gif)

**Comment by 4ndrey** [comment]
Will be solved in https://github.com/bmw-tech/widget_driver/pull/82

**Comment by 4ndrey** [comment]
will be auto-solved with next version increase
