### ISSUE TITLE
The version of generator which was used to generate the code is not working

### ISSUE THREAD

**Issue by robert-northmind** [bmw-tech/widget_driver#91]
**Describe the bug**
When we generate the TestDriver then we add a line in the generated code which says which version of the generator that was used to create the file.

This is not working. The version number which we print there, that is the version number of the flutter app which is using the generator. Not the version number of the generator.

**To Reproduce**
1. Create new Driver
2. Annotate the driver so that a TestDriver will be generated
3. Look in the generated *.g.dart file
4. Looks at the line which says: `This file was generated with widget_driver_generator version: ...`
5. Verify that that version number is not the version number of the widget_driver_generator

**Expected behavior**
The version we print there should be the version number of the widget_driver_generator.

**Screenshots**
![Screenshot 2023-01-20 at 13 45 36](https://user-images.githubusercontent.com/59053438/213698158-23a89c95-270d-4365-a856-f3ffd0e386a5.png)

**System info (please complete the following information):**
 - Flutter version: 3.3.8
 - widget_driver_generator version: 0.0.2

**Additional context**
Maybe it is not possible to grab the version number of the widget_driver_generator.
But in that case maybe we should change the generator logic to have a date when it was generated instead maybe?

**Comment by devmil** [comment]
I stumbled across an approach for getting the own version number in the Melos repository.
They use the Melos hooks (of course 😁) to generate a constant containing the version.
Hook: https://github.com/invertase/melos/blob/1a5c8547fd1c41640a1f15ae79fe8303ead40eea/melos.yaml#L19
Constant generation: https://github.com/invertase/melos/blob/1a5c8547fd1c41640a1f15ae79fe8303ead40eea/scripts/generate_version.dart#L19
Constant: https://github.com/invertase/melos/blob/main/packages/melos/lib/version.g.dart
